name: Build Project

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  build:
    name: Build frontend project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          BASE_API_URL: ${{ secrets.BASE_API_URL || 'https://api.eduva.example.com' }}
          CLIENT_URL: ${{ secrets.CLIENT_URL || 'https://api.eduva.example.com' }}
        run: npm run build
